import Vue from 'vue'
window.Vue = Vue;
import Vuex from 'vuex';
Vue.use(Vuex);
window.Vuex = Vuex;
import VueRouter from 'vue-router';
Vue.use(VueRouter);
window.VueRouter = VueRouter;
// import iView from 'bh-iview';
// Vue.use(iView);
import tgTuring from 'tg-turing';
Vue.use(tgTuring);
window["tg-turing"] = tgTuring;
import tgTuringAntd from 'tg-turing-antd';
Vue.use(tgTuringAntd);

import 'core-js/features/object/assign';
import 'core-js/features/object/entries';
import 'core-js/features/object/get-own-property-descriptor';
import 'core-js/features/object/is';
import 'core-js/features/object/set-prototype-of';
import 'core-js/features/object/values';
import 'core-js/features/array/copy-within';
import 'core-js/features/array/entries';
import 'core-js/features/array/fill';
import 'core-js/features/array/find';
import 'core-js/features/array/find-index';
import 'core-js/features/array/flat';
import 'core-js/features/array/flat-map';
import 'core-js/features/array/from';
import 'core-js/features/array/includes';
import 'core-js/features/array/keys';
import 'core-js/features/array/of';
import 'core-js/features/string/anchor';
import 'core-js/features/string/code-point-at';
import 'core-js/features/string/ends-with';
import 'core-js/features/string/from-code-point';
import 'core-js/features/string/includes';
import 'core-js/features/string/pad-end';
import 'core-js/features/string/pad-start';
import 'core-js/features/string/raw';
import 'core-js/features/string/repeat';
import 'core-js/features/string/starts-with';
import 'core-js/features/string/trim-end';
import 'core-js/features/string/trim-start';
import 'core-js/features/promise';
import 'core-js/features/reflect';


import 'tg-turing/dist/css/default/tg-turing.min.css';
import 'tg-turing/dist/style/default/tg-turing.css';
import 'tg-turing-antd/dist/tg-turing-antd.min.css';